import bcrypt from "bcryptjs";
import { ChecklistSection, PrismaClient, UserRole } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const passwordHash = await bcrypt.hash("fedshield123", 10);

  const users = [
    {
      email: "admin@fedshield.local",
      fullName: "Admin FedShield",
      role: UserRole.admin,
      passwordHash,
    },
    {
      email: "senior@fedshield.local",
      fullName: "Senior Consulente",
      role: UserRole.senior,
      passwordHash,
    },
    {
      email: "junior@fedshield.local",
      fullName: "Junior Consulente",
      role: UserRole.junior,
      passwordHash,
    },
  ];

  for (const user of users) {
    await prisma.user.upsert({
      where: { email: user.email },
      update: user,
      create: user,
    });
  }

  await prisma.company.upsert({
    where: { vatNumber: "IT00000000001" },
    update: {
      name: "Ristorante Demo S.r.l.",
      atecoCode: "56.10.11",
      city: "Milano",
    },
    create: {
      name: "Ristorante Demo S.r.l.",
      vatNumber: "IT00000000001",
      atecoCode: "56.10.11",
      city: "Milano",
    },
  });

  await prisma.checklistTemplate.deleteMany({
    where: {
      id: {
        in: [
          "haccp-template-seed",
          "horeca-premises-template-seed",
          "horeca-procedures-template-seed",
        ],
      },
    },
  });

  const generalTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "general-template-seed" },
    update: {
      name: "Checklist Generale Antisanzione",
      description: "Requisiti trasversali sicurezza e compliance",
      macroGroup: "ALL",
      isGeneral: true,
      atecoCode: null,
      isActive: true,
    },
    create: {
      id: "general-template-seed",
      name: "Checklist Generale Antisanzione",
      description: "Requisiti trasversali sicurezza e compliance",
      macroGroup: "ALL",
      isGeneral: true,
      isActive: true,
    },
  });

  const restaurantPremisesTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "restaurant-premises-template-seed" },
    update: {
      name: "Checklist Ristorante - Locali e Attrezzature",
      description: "Controlli strutturali, impiantistici e tecnici dei locali",
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
      isGeneral: false,
      isActive: true,
    },
    create: {
      id: "restaurant-premises-template-seed",
      name: "Checklist Ristorante - Locali e Attrezzature",
      description: "Controlli strutturali, impiantistici e tecnici dei locali",
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
      isGeneral: false,
      isActive: true,
    },
  });

  const restaurantProceduresTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "restaurant-procedures-template-seed" },
    update: {
      name: "Checklist Ristorante - Procedure e Igiene",
      description: "Controlli operativi HACCP, igiene e procedure di lavoro",
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
      isGeneral: false,
      isActive: true,
    },
    create: {
      id: "restaurant-procedures-template-seed",
      name: "Checklist Ristorante - Procedure e Igiene",
      description: "Controlli operativi HACCP, igiene e procedure di lavoro",
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
      isGeneral: false,
      isActive: true,
    },
  });

  const barPremisesTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "bar-premises-template-seed" },
    update: {
      name: "Checklist Bar - Locali e Attrezzature",
      description: "Controlli strutturali, impiantistici e tecnici per bar e caffetterie",
      atecoCode: "56.30",
      macroGroup: "BAR",
      isGeneral: false,
      isActive: true,
    },
    create: {
      id: "bar-premises-template-seed",
      name: "Checklist Bar - Locali e Attrezzature",
      description: "Controlli strutturali, impiantistici e tecnici per bar e caffetterie",
      atecoCode: "56.30",
      macroGroup: "BAR",
      isGeneral: false,
      isActive: true,
    },
  });

  const barProceduresTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "bar-procedures-template-seed" },
    update: {
      name: "Checklist Bar - Procedure e Igiene",
      description: "Controlli operativi HACCP, igiene e procedure di lavoro per bar",
      atecoCode: "56.30",
      macroGroup: "BAR",
      isGeneral: false,
      isActive: true,
    },
    create: {
      id: "bar-procedures-template-seed",
      name: "Checklist Bar - Procedure e Igiene",
      description: "Controlli operativi HACCP, igiene e procedure di lavoro per bar",
      atecoCode: "56.30",
      macroGroup: "BAR",
      isGeneral: false,
      isActive: true,
    },
  });

  await prisma.checklistItem.deleteMany({
    where: {
      templateId: {
        in: [
          generalTemplate.id,
          restaurantPremisesTemplate.id,
          restaurantProceduresTemplate.id,
          barPremisesTemplate.id,
          barProceduresTemplate.id,
        ],
      },
    },
  });

  const generalItems = [
    {
      templateId: generalTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.premises_equipment,
      area: "Documentazione sicurezza",
      question: "DVR aggiornato, firmato e coerente con le mansioni presenti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.premises_equipment,
      area: "Organizzazione sicurezza",
      question: "Nomine RSPP, addetti antincendio e primo soccorso formalizzate?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.procedures_hygiene,
      area: "Formazione",
      question: "Formazione sicurezza lavoratori, preposti e aggiornamenti in regola?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.premises_equipment,
      area: "Sorveglianza sanitaria",
      question: "Sorveglianza sanitaria attiva con giudizi di idoneita disponibili?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Dichiarazioni conformita impianti elettrico e gas disponibili?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.procedures_hygiene,
      area: "Emergenze",
      question: "Piano emergenza, prove evacuazione e istruzioni operative presenti?",
      defaultSeverity: 3,
      defaultSanctionable: false,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Registro manutenzione attrezzature e presidi disponibile e aggiornato?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.procedures_hygiene,
      area: "Appalti",
      question: "Gestione imprese esterne con DUVRI/procedure di coordinamento quando dovuto?",
      defaultSeverity: 3,
      defaultSanctionable: false,
    },
  ];

  const restaurantPremisesItems = [
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Layout del ristorante idoneo alla separazione sporco/pulito e crudo/cotto?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Pavimenti, pareti e soffitti integri, pulibili e privi di deterioramenti?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Porte/finestre con sistemi anti infestanti e buona tenuta strutturale?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Ventilazione e aspirazione in cucina adeguate e manutenute?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Illuminazione sufficiente in aree preparazione, lavaggio e deposito?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Rete idrica con disponibilita di acqua potabile e punti lavamani dedicati?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Scarichi e sifoni funzionanti senza reflussi o ristagni anomali?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza antincendio",
      question: "Presidi antincendio presenti, segnalati e manutenuti entro scadenza?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 9,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza antincendio",
      question: "Vie di esodo libere, uscite di emergenza accessibili e segnaletica presente?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 10,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza lavoro",
      question: "Cassetta primo soccorso completa e facilmente accessibile?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 11,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Attrezzature di cottura in sicurezza con protezioni e stato manutentivo idoneo?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 12,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Frigoriferi, congelatori e abbattitore efficienti con termometri funzionanti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 13,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Attrezzature di taglio con dispositivi di sicurezza integri e operativi?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 14,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Utensili a contatto alimenti integri, puliti e conservati correttamente?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 15,
      section: ChecklistSection.premises_equipment,
      area: "Stoccaggio",
      question: "Magazzino asciutto e ordinato con alimenti separati da chimici e materiali sporchi?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 16,
      section: ChecklistSection.premises_equipment,
      area: "Stoccaggio",
      question: "Scaffalature idonee con alimenti sollevati da terra e separazione allergeni?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 17,
      section: ChecklistSection.premises_equipment,
      area: "Spogliatoi e servizi",
      question: "Spogliatoi e servizi per personale adeguati e mantenuti in condizioni igieniche?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 18,
      section: ChecklistSection.premises_equipment,
      area: "Rifiuti",
      question: "Contenitori rifiuti idonei, chiusi e collocati in aree dedicate?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 19,
      section: ChecklistSection.premises_equipment,
      area: "Rifiuti",
      question: "Gestione oli esausti con contenitori dedicati e tracciabilita smaltimento?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 20,
      section: ChecklistSection.premises_equipment,
      area: "Infestanti",
      question: "Piano derattizzazione/disinfestazione attivo con evidenze di monitoraggio?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
  ];

  const restaurantProcedureItems = [
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Manuale HACCP aggiornato e coerente con menu, processi e layout reali?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Analisi pericoli e CCP/CP formalizzati con limiti critici definiti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Registri temperature conservazione compilati regolarmente e firmati?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Monitoraggi temperature cottura/rigenerazione con soglie interne definite?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Procedure abbattimento/raffreddamento rapido applicate e registrate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.procedures_hygiene,
      area: "Allergeni",
      question: "Gestione allergeni formalizzata con mappatura ingredienti e menu aggiornato?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.procedures_hygiene,
      area: "Allergeni",
      question: "Procedure operative per evitare contaminazione crociata allergeni rispettate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.procedures_hygiene,
      area: "Rintracciabilita",
      question: "Schede fornitori, lotti e tracciabilita ingredienti conservate correttamente?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 9,
      section: ChecklistSection.procedures_hygiene,
      area: "Rintracciabilita",
      question: "Gestione richiami/ritiri alimentari prevista da procedura interna?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 10,
      section: ChecklistSection.procedures_hygiene,
      area: "Ricevimento merci",
      question: "Controlli in accettazione su temperatura, imballi, scadenze e integrita effettuati?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 11,
      section: ChecklistSection.procedures_hygiene,
      area: "Ricevimento merci",
      question: "Procedura respingimento merci non conformi formalizzata e utilizzata?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 12,
      section: ChecklistSection.procedures_hygiene,
      area: "Produzione alimenti",
      question: "Separazione operativa tra alimenti crudi e cotti rispettata nelle fasi di lavoro?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 13,
      section: ChecklistSection.procedures_hygiene,
      area: "Produzione alimenti",
      question: "Tempi di esposizione a temperatura ambiente contenuti e controllati?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 14,
      section: ChecklistSection.procedures_hygiene,
      area: "Igiene personale",
      question: "Operatori con abbigliamento idoneo, cuffie e comportamento igienico corretto?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 15,
      section: ChecklistSection.procedures_hygiene,
      area: "Igiene personale",
      question: "Protocollo lavaggio mani applicato con disponibilita detergenti/asciugatura?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 16,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Piano pulizie e sanificazioni con frequenze, responsabilita e registrazioni?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 17,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Prodotti detergenti/disinfettanti corretti, etichettati e separati dagli alimenti?",
      defaultSeverity: 3,
      defaultSanctionable: false,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 18,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Sanificazione utensili e taglieri effettuata con metodo verificabile?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 19,
      section: ChecklistSection.procedures_hygiene,
      area: "Formazione HACCP",
      question: "Formazione HACCP personale in corso di validita e verificabile per tutti gli addetti?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 20,
      section: ChecklistSection.procedures_hygiene,
      area: "Miglioramento",
      question: "Registro NC interne con azioni correttive e tempi di chiusura monitorati?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
  ];

  const barPremisesItems = [
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Layout del bar idoneo alla separazione area servizio, area preparazione e deposito?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Pavimenti, pareti e superfici di lavoro integri, lavabili e mantenuti in buono stato?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Aree esterne/dehors gestite in sicurezza con passaggi liberi e assenza rischi evidenti?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Impianto elettrico e prese al banco in condizioni sicure, senza cavi volanti o adattamenti impropri?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Ventilazione/aspirazione aree preparazione adeguata e manutenuta?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Punti acqua potabile e lavamani dedicati presenti e funzionanti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza antincendio",
      question: "Estintori e presidi antincendio presenti, segnalati e con manutenzione in corso di validita?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza antincendio",
      question: "Vie di esodo e uscite di emergenza sempre libere e correttamente segnalate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 9,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza lavoro",
      question: "Cassetta di primo soccorso disponibile, completa e accessibile al personale?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 10,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Macchina caffe e macinadosatore in buono stato, con manutenzioni registrate?",
      defaultSeverity: 3,
      defaultSanctionable: false,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 11,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Lavabicchieri/lavastoviglie funzionanti con programmi adeguati e controlli minimi di efficacia?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 12,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Frigoriferi e vetrine refrigerate efficienti con termometri funzionanti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 13,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Macchine per ghiaccio e relativi filtri mantenuti in condizioni igieniche adeguate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 14,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Impianto spillatura bevande e bombole CO2 in sicurezza con controlli periodici documentati?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 15,
      section: ChecklistSection.premises_equipment,
      area: "Stoccaggio",
      question: "Magazzino bevande/alimenti ordinato con separazione prodotti alimentari e chimici?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 16,
      section: ChecklistSection.premises_equipment,
      area: "Stoccaggio",
      question: "Prodotti e semilavorati etichettati con data apertura/scadenza interna quando necessario?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 17,
      section: ChecklistSection.premises_equipment,
      area: "Spogliatoi e servizi",
      question: "Servizi igienici personale/clienti adeguati e mantenuti in condizioni igieniche idonee?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 18,
      section: ChecklistSection.premises_equipment,
      area: "Rifiuti",
      question: "Gestione rifiuti con contenitori idonei, differenziati e regolare svuotamento?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 19,
      section: ChecklistSection.premises_equipment,
      area: "Rifiuti",
      question: "Vetro e imballaggi gestiti in sicurezza evitando accumuli in aree operative?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 20,
      section: ChecklistSection.premises_equipment,
      area: "Infestanti",
      question: "Piano derattizzazione/disinfestazione attivo con evidenze di monitoraggio periodico?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
  ];

  const barProcedureItems = [
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Manuale HACCP aggiornato e coerente con attivita reali (caffetteria, bevande, alimenti pronti)?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Analisi pericoli e punti di controllo definiti per prodotti freddi/caldi, latte e ghiaccio?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Registri temperature frigoriferi/vetrine compilati regolarmente e verificabili?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Procedure di controllo latte, creme e prodotti deperibili applicate con evidenze?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Gestione igienica ghiaccio alimentare definita (produzione, prelievo, conservazione)?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.procedures_hygiene,
      area: "Allergeni",
      question: "Elenco allergeni aggiornato e comunicato al consumatore per alimenti e bevande somministrate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.procedures_hygiene,
      area: "Allergeni",
      question: "Procedure operative per prevenire contaminazioni crociate allergeniche applicate al banco?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.procedures_hygiene,
      area: "Rintracciabilita",
      question: "Tracciabilita lotti e fornitori disponibile per alimenti, ingredienti e bevande?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 9,
      section: ChecklistSection.procedures_hygiene,
      area: "Rintracciabilita",
      question: "Procedura interna per ritiro/richiamo prodotti non conformi formalizzata e nota al personale?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 10,
      section: ChecklistSection.procedures_hygiene,
      area: "Ricevimento merci",
      question: "Controlli in accettazione merci su temperatura, integrita imballi e scadenze eseguiti?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 11,
      section: ChecklistSection.procedures_hygiene,
      area: "Ricevimento merci",
      question: "Respingimento merci non conformi gestito con procedura documentata?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 12,
      section: ChecklistSection.procedures_hygiene,
      area: "Preparazioni banco",
      question: "Preparazione panini/snack e guarnizioni con separazione utensili e superfici pulite?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 13,
      section: ChecklistSection.procedures_hygiene,
      area: "Preparazioni banco",
      question: "Tempi di permanenza a temperatura ambiente per alimenti deperibili ridotti e controllati?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 14,
      section: ChecklistSection.procedures_hygiene,
      area: "Igiene personale",
      question: "Personale con abbigliamento idoneo e comportamenti igienici adeguati durante il servizio?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 15,
      section: ChecklistSection.procedures_hygiene,
      area: "Igiene personale",
      question: "Procedura lavaggio mani applicata con disponibilita di detergente e asciugatura igienica?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 16,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Piano pulizie/sanificazioni del banco, macchina caffe, lavabicchieri e attrezzature formalizzato?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 17,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Prodotti detergenti/disinfettanti etichettati e conservati separatamente dagli alimenti?",
      defaultSeverity: 3,
      defaultSanctionable: false,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 18,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Sanificazione bicchieri e utensili verificata con criteri minimi di efficacia?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 19,
      section: ChecklistSection.procedures_hygiene,
      area: "Formazione HACCP",
      question: "Formazione HACCP del personale valida e documentata per tutti gli addetti coinvolti?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 20,
      section: ChecklistSection.procedures_hygiene,
      area: "Miglioramento",
      question: "Registro NC interne con azioni correttive e verifica delle chiusure disponibile?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
  ];

  for (const item of [
    ...generalItems,
    ...restaurantPremisesItems,
    ...restaurantProcedureItems,
    ...barPremisesItems,
    ...barProcedureItems,
  ]) {
    await prisma.checklistItem.create({
      data: item,
    });
  }

  await prisma.documentTemplate.deleteMany({});

  const documentTemplates = [
    {
      name: "Visura camerale aggiornata",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Planimetria aggiornata dei locali",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Relazione tecnica attivita",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "UNILAV dipendenti",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "DVR e allegati (rischi specifici ristorazione)",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Nomina RSPP e deleghe sicurezza",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Nomina addetti antincendio e primo soccorso",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Attestati formazione sicurezza lavoratori",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Sorveglianza sanitaria e giudizi di idoneita",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Dichiarazioni conformita impianti elettrico e gas",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Registro manutenzioni attrezzature",
      isGeneral: true,
      isRequired: false,
    },
    {
      name: "SCIA / notifica sanitaria attivita alimentare",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Manuale HACCP aggiornato",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Analisi pericoli e piano CCP/CP",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Registro temperature celle/frigoriferi/abbattitore",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Registro temperature cottura/rigenerazione",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Piano pulizie e sanificazioni con registrazioni",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Procedure gestione allergeni e menu allergeni",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Schede tracciabilita lotti e fornitori",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Procedura ritiro/richiamo alimenti",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Attestati formazione HACCP personale",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Contratto e rapporti derattizzazione/disinfestazione",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Certificazioni cappa/aspirazione e manutenzioni",
      isGeneral: false,
      isRequired: false,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Documenti gestione oli esausti e smaltimento",
      isGeneral: false,
      isRequired: false,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "SCIA / notifica sanitaria attivita bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Manuale HACCP bar aggiornato",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Analisi pericoli e punti di controllo bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Registro temperature frigoriferi e vetrine bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Procedura e controlli gestione ghiaccio alimentare",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Piano pulizie e sanificazioni banco/macchina caffe/lavabicchieri",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Procedure gestione allergeni per alimenti e bevande",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Schede tracciabilita lotti e fornitori bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Procedura ritiro/richiamo prodotti bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Attestati formazione HACCP personale bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Registro manutenzioni impianto spillatura e bombole CO2",
      isGeneral: false,
      isRequired: false,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Contratto e rapporti derattizzazione/disinfestazione bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
  ];

  await prisma.documentTemplate.createMany({
    data: documentTemplates.map((doc) => ({
      name: doc.name,
      description: `Template documento: ${doc.name}`,
      isGeneral: doc.isGeneral,
      isRequired: doc.isRequired,
      atecoCode: doc.atecoCode ?? null,
      macroGroup: doc.macroGroup ?? null,
      isActive: true,
    })),
  });

  console.log("Seed completato.");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
