import bcrypt from "bcryptjs";
import { ChecklistSection, ComplianceDomain, PrismaClient, UserRole } from "@prisma/client";

const prisma = new PrismaClient();

function inferChecklistDomain(area: string, question: string): ComplianceDomain {
  const text = `${area} ${question}`.toLowerCase();
  const haccpKeywords = [
    "haccp",
    "allergen",
    "temperatur",
    "ccp",
    "cp",
    "rintracciabil",
    "ritiro",
    "richiamo",
    "ricevimento merci",
    "crudo",
    "cotto",
    "abbatt",
    "sanific",
    "igien",
    "aliment",
    "frigor",
    "congel",
    "vetrine refrigerate",
    "ghiaccio",
    "lotti",
    "menu",
    "deperibil",
    "deratt",
    "disinfest",
    "contaminazione",
    "pulizie",
    "stoccaggio",
  ];
  const safetyKeywords = [
    "dvr",
    "rspp",
    "antincendio",
    "incendio",
    "evacuazione",
    "primo soccorso",
    "sorveglianza sanitaria",
    "impiant",
    "duvri",
    "idoneita",
    "uscite di emergenza",
    "vie di esodo",
    "dispositivi di sicurezza",
    "cassetta",
    "co2",
    "spogliatoi",
    "ascensor",
    "housekeeping",
    "carichi",
    "scale",
  ];

  const hasHaccp = haccpKeywords.some((keyword) => text.includes(keyword));
  const hasSafety = safetyKeywords.some((keyword) => text.includes(keyword));

  if (hasHaccp && hasSafety) return ComplianceDomain.both;
  if (hasHaccp) return ComplianceDomain.haccp;
  if (hasSafety) return ComplianceDomain.safety;
  return ComplianceDomain.both;
}

function inferDocumentDomain(name: string): ComplianceDomain {
  const text = name.toLowerCase();
  const haccpKeywords = [
    "haccp",
    "allergen",
    "temperatur",
    "tracciabil",
    "ritiro",
    "richiamo",
    "sanific",
    "ghiaccio",
    "aliment",
    "deratt",
    "disinfest",
  ];
  const safetyKeywords = [
    "dvr",
    "rspp",
    "antincendio",
    "incendio",
    "evacuazione",
    "primo soccorso",
    "sorveglianza sanitaria",
    "impiant",
    "unilav",
    "manutenzion",
    "ascensor",
  ];

  const hasHaccp = haccpKeywords.some((keyword) => text.includes(keyword));
  const hasSafety = safetyKeywords.some((keyword) => text.includes(keyword));

  if (hasHaccp && hasSafety) return ComplianceDomain.both;
  if (hasHaccp) return ComplianceDomain.haccp;
  if (hasSafety) return ComplianceDomain.safety;
  return ComplianceDomain.both;
}

async function main() {
  const passwordHash = await bcrypt.hash("fedshield123", 10);

  const users = [
    {
      email: "admin@fedshield.local",
      fullName: "Admin FedShield",
      role: UserRole.admin,
      passwordHash,
    },
    {
      email: "senior@fedshield.local",
      fullName: "Senior Consulente",
      role: UserRole.senior,
      passwordHash,
    },
    {
      email: "junior@fedshield.local",
      fullName: "Junior Consulente",
      role: UserRole.junior,
      passwordHash,
    },
  ];

  for (const user of users) {
    await prisma.user.upsert({
      where: { email: user.email },
      update: user,
      create: user,
    });
  }

  await prisma.company.upsert({
    where: { vatNumber: "IT00000000001" },
    update: {
      name: "Ristorante Demo S.r.l.",
      atecoCode: "56.10.11",
      city: "Milano",
    },
    create: {
      name: "Ristorante Demo S.r.l.",
      vatNumber: "IT00000000001",
      atecoCode: "56.10.11",
      city: "Milano",
    },
  });

  await prisma.checklistTemplate.deleteMany({
    where: {
      id: {
        in: [
          "haccp-template-seed",
          "horeca-premises-template-seed",
          "horeca-procedures-template-seed",
        ],
      },
    },
  });

  const generalTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "general-template-seed" },
    update: {
      name: "Checklist Generale Antisanzione",
      description: "Requisiti trasversali sicurezza e compliance",
      macroGroup: "ALL",
      isGeneral: true,
      atecoCode: null,
      isActive: true,
    },
    create: {
      id: "general-template-seed",
      name: "Checklist Generale Antisanzione",
      description: "Requisiti trasversali sicurezza e compliance",
      macroGroup: "ALL",
      isGeneral: true,
      isActive: true,
    },
  });

  const restaurantPremisesTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "restaurant-premises-template-seed" },
    update: {
      name: "Checklist Ristorante - Locali e Attrezzature",
      description: "Controlli strutturali, impiantistici e tecnici dei locali",
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
      isGeneral: false,
      isActive: true,
    },
    create: {
      id: "restaurant-premises-template-seed",
      name: "Checklist Ristorante - Locali e Attrezzature",
      description: "Controlli strutturali, impiantistici e tecnici dei locali",
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
      isGeneral: false,
      isActive: true,
    },
  });

  const restaurantProceduresTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "restaurant-procedures-template-seed" },
    update: {
      name: "Checklist Ristorante - Procedure e Igiene",
      description: "Controlli operativi HACCP, igiene e procedure di lavoro",
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
      isGeneral: false,
      isActive: true,
    },
    create: {
      id: "restaurant-procedures-template-seed",
      name: "Checklist Ristorante - Procedure e Igiene",
      description: "Controlli operativi HACCP, igiene e procedure di lavoro",
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
      isGeneral: false,
      isActive: true,
    },
  });

  const barPremisesTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "bar-premises-template-seed" },
    update: {
      name: "Checklist Bar - Locali e Attrezzature",
      description: "Controlli strutturali, impiantistici e tecnici per bar e caffetterie",
      atecoCode: "56.30",
      macroGroup: "BAR",
      isGeneral: false,
      isActive: true,
    },
    create: {
      id: "bar-premises-template-seed",
      name: "Checklist Bar - Locali e Attrezzature",
      description: "Controlli strutturali, impiantistici e tecnici per bar e caffetterie",
      atecoCode: "56.30",
      macroGroup: "BAR",
      isGeneral: false,
      isActive: true,
    },
  });

  const barProceduresTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "bar-procedures-template-seed" },
    update: {
      name: "Checklist Bar - Procedure e Igiene",
      description: "Controlli operativi HACCP, igiene e procedure di lavoro per bar",
      atecoCode: "56.30",
      macroGroup: "BAR",
      isGeneral: false,
      isActive: true,
    },
    create: {
      id: "bar-procedures-template-seed",
      name: "Checklist Bar - Procedure e Igiene",
      description: "Controlli operativi HACCP, igiene e procedure di lavoro per bar",
      atecoCode: "56.30",
      macroGroup: "BAR",
      isGeneral: false,
      isActive: true,
    },
  });

  const hotelPremisesTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "hotel-premises-template-seed" },
    update: {
      name: "Checklist Hotel - Locali e Attrezzature",
      description: "Controlli strutturali, impiantistici e tecnici per hotel e alberghi",
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
      isGeneral: false,
      isActive: true,
    },
    create: {
      id: "hotel-premises-template-seed",
      name: "Checklist Hotel - Locali e Attrezzature",
      description: "Controlli strutturali, impiantistici e tecnici per hotel e alberghi",
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
      isGeneral: false,
      isActive: true,
    },
  });

  const hotelProceduresTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "hotel-procedures-template-seed" },
    update: {
      name: "Checklist Hotel - Procedure e Igiene",
      description: "Controlli operativi HACCP, igiene e procedure di lavoro per strutture ricettive",
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
      isGeneral: false,
      isActive: true,
    },
    create: {
      id: "hotel-procedures-template-seed",
      name: "Checklist Hotel - Procedure e Igiene",
      description: "Controlli operativi HACCP, igiene e procedure di lavoro per strutture ricettive",
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
      isGeneral: false,
      isActive: true,
    },
  });

  const pastryPremisesTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "pastry-premises-template-seed" },
    update: {
      name: "Checklist Pasticceria/Gelateria - Locali e Attrezzature",
      description: "Controlli strutturali, impiantistici e tecnici per laboratorio e banco vendita",
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
      isGeneral: false,
      isActive: true,
    },
    create: {
      id: "pastry-premises-template-seed",
      name: "Checklist Pasticceria/Gelateria - Locali e Attrezzature",
      description: "Controlli strutturali, impiantistici e tecnici per laboratorio e banco vendita",
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
      isGeneral: false,
      isActive: true,
    },
  });

  const pastryProceduresTemplate = await prisma.checklistTemplate.upsert({
    where: { id: "pastry-procedures-template-seed" },
    update: {
      name: "Checklist Pasticceria/Gelateria - Procedure e Igiene",
      description: "Controlli operativi HACCP, GMP e sicurezza per produzione e vendita",
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
      isGeneral: false,
      isActive: true,
    },
    create: {
      id: "pastry-procedures-template-seed",
      name: "Checklist Pasticceria/Gelateria - Procedure e Igiene",
      description: "Controlli operativi HACCP, GMP e sicurezza per produzione e vendita",
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
      isGeneral: false,
      isActive: true,
    },
  });

  await prisma.checklistItem.deleteMany({
    where: {
      templateId: {
        in: [
          generalTemplate.id,
          restaurantPremisesTemplate.id,
          restaurantProceduresTemplate.id,
          barPremisesTemplate.id,
          barProceduresTemplate.id,
          hotelPremisesTemplate.id,
          hotelProceduresTemplate.id,
          pastryPremisesTemplate.id,
          pastryProceduresTemplate.id,
        ],
      },
    },
  });

  const generalItems = [
    {
      templateId: generalTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.premises_equipment,
      area: "Documentazione sicurezza",
      question: "DVR aggiornato, firmato e coerente con le mansioni presenti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.premises_equipment,
      area: "Organizzazione sicurezza",
      question: "Nomine RSPP, addetti antincendio e primo soccorso formalizzate?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.procedures_hygiene,
      area: "Formazione",
      question: "Formazione sicurezza lavoratori, preposti e aggiornamenti in regola?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.premises_equipment,
      area: "Sorveglianza sanitaria",
      question: "Sorveglianza sanitaria attiva con giudizi di idoneita disponibili?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Dichiarazioni conformita impianti elettrico e gas disponibili?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.procedures_hygiene,
      area: "Emergenze",
      question: "Piano emergenza, prove evacuazione e istruzioni operative presenti?",
      defaultSeverity: 3,
      defaultSanctionable: false,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Registro manutenzione attrezzature e presidi disponibile e aggiornato?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: generalTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.procedures_hygiene,
      area: "Appalti",
      question: "Gestione imprese esterne con DUVRI/procedure di coordinamento quando dovuto?",
      defaultSeverity: 3,
      defaultSanctionable: false,
    },
  ];

  const restaurantPremisesItems = [
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Layout del ristorante idoneo alla separazione sporco/pulito e crudo/cotto?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Pavimenti, pareti e soffitti integri, pulibili e privi di deterioramenti?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Porte/finestre con sistemi anti infestanti e buona tenuta strutturale?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Ventilazione e aspirazione in cucina adeguate e manutenute?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Illuminazione sufficiente in aree preparazione, lavaggio e deposito?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Rete idrica con disponibilita di acqua potabile e punti lavamani dedicati?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Scarichi e sifoni funzionanti senza reflussi o ristagni anomali?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza antincendio",
      question: "Presidi antincendio presenti, segnalati e manutenuti entro scadenza?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 9,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza antincendio",
      question: "Vie di esodo libere, uscite di emergenza accessibili e segnaletica presente?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 10,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza lavoro",
      question: "Cassetta primo soccorso completa e facilmente accessibile?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 11,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Attrezzature di cottura in sicurezza con protezioni e stato manutentivo idoneo?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 12,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Frigoriferi, congelatori e abbattitore efficienti con termometri funzionanti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 13,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Attrezzature di taglio con dispositivi di sicurezza integri e operativi?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 14,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Utensili a contatto alimenti integri, puliti e conservati correttamente?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 15,
      section: ChecklistSection.premises_equipment,
      area: "Stoccaggio",
      question: "Magazzino asciutto e ordinato con alimenti separati da chimici e materiali sporchi?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 16,
      section: ChecklistSection.premises_equipment,
      area: "Stoccaggio",
      question: "Scaffalature idonee con alimenti sollevati da terra e separazione allergeni?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 17,
      section: ChecklistSection.premises_equipment,
      area: "Spogliatoi e servizi",
      question: "Spogliatoi e servizi per personale adeguati e mantenuti in condizioni igieniche?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 18,
      section: ChecklistSection.premises_equipment,
      area: "Rifiuti",
      question: "Contenitori rifiuti idonei, chiusi e collocati in aree dedicate?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 19,
      section: ChecklistSection.premises_equipment,
      area: "Rifiuti",
      question: "Gestione oli esausti con contenitori dedicati e tracciabilita smaltimento?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: restaurantPremisesTemplate.id,
      orderIndex: 20,
      section: ChecklistSection.premises_equipment,
      area: "Infestanti",
      question: "Piano derattizzazione/disinfestazione attivo con evidenze di monitoraggio?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
  ];

  const restaurantProcedureItems = [
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Manuale HACCP aggiornato e coerente con menu, processi e layout reali?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Analisi pericoli e CCP/CP formalizzati con limiti critici definiti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Registri temperature conservazione compilati regolarmente e firmati?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Monitoraggi temperature cottura/rigenerazione con soglie interne definite?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Procedure abbattimento/raffreddamento rapido applicate e registrate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.procedures_hygiene,
      area: "Allergeni",
      question: "Gestione allergeni formalizzata con mappatura ingredienti e menu aggiornato?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.procedures_hygiene,
      area: "Allergeni",
      question: "Procedure operative per evitare contaminazione crociata allergeni rispettate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.procedures_hygiene,
      area: "Rintracciabilita",
      question: "Schede fornitori, lotti e tracciabilita ingredienti conservate correttamente?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 9,
      section: ChecklistSection.procedures_hygiene,
      area: "Rintracciabilita",
      question: "Gestione richiami/ritiri alimentari prevista da procedura interna?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 10,
      section: ChecklistSection.procedures_hygiene,
      area: "Ricevimento merci",
      question: "Controlli in accettazione su temperatura, imballi, scadenze e integrita effettuati?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 11,
      section: ChecklistSection.procedures_hygiene,
      area: "Ricevimento merci",
      question: "Procedura respingimento merci non conformi formalizzata e utilizzata?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 12,
      section: ChecklistSection.procedures_hygiene,
      area: "Produzione alimenti",
      question: "Separazione operativa tra alimenti crudi e cotti rispettata nelle fasi di lavoro?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 13,
      section: ChecklistSection.procedures_hygiene,
      area: "Produzione alimenti",
      question: "Tempi di esposizione a temperatura ambiente contenuti e controllati?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 14,
      section: ChecklistSection.procedures_hygiene,
      area: "Igiene personale",
      question: "Operatori con abbigliamento idoneo, cuffie e comportamento igienico corretto?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 15,
      section: ChecklistSection.procedures_hygiene,
      area: "Igiene personale",
      question: "Protocollo lavaggio mani applicato con disponibilita detergenti/asciugatura?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 16,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Piano pulizie e sanificazioni con frequenze, responsabilita e registrazioni?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 17,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Prodotti detergenti/disinfettanti corretti, etichettati e separati dagli alimenti?",
      defaultSeverity: 3,
      defaultSanctionable: false,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 18,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Sanificazione utensili e taglieri effettuata con metodo verificabile?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 19,
      section: ChecklistSection.procedures_hygiene,
      area: "Formazione HACCP",
      question: "Formazione HACCP personale in corso di validita e verificabile per tutti gli addetti?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: restaurantProceduresTemplate.id,
      orderIndex: 20,
      section: ChecklistSection.procedures_hygiene,
      area: "Miglioramento",
      question: "Registro NC interne con azioni correttive e tempi di chiusura monitorati?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
  ];

  const barPremisesItems = [
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Layout del bar idoneo alla separazione area servizio, area preparazione e deposito?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Pavimenti, pareti e superfici di lavoro integri, lavabili e mantenuti in buono stato?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Aree esterne/dehors gestite in sicurezza con passaggi liberi e assenza rischi evidenti?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Impianto elettrico e prese al banco in condizioni sicure, senza cavi volanti o adattamenti impropri?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Ventilazione/aspirazione aree preparazione adeguata e manutenuta?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Punti acqua potabile e lavamani dedicati presenti e funzionanti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza antincendio",
      question: "Estintori e presidi antincendio presenti, segnalati e con manutenzione in corso di validita?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza antincendio",
      question: "Vie di esodo e uscite di emergenza sempre libere e correttamente segnalate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 9,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza lavoro",
      question: "Cassetta di primo soccorso disponibile, completa e accessibile al personale?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 10,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Macchina caffe e macinadosatore in buono stato, con manutenzioni registrate?",
      defaultSeverity: 3,
      defaultSanctionable: false,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 11,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Lavabicchieri/lavastoviglie funzionanti con programmi adeguati e controlli minimi di efficacia?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 12,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Frigoriferi e vetrine refrigerate efficienti con termometri funzionanti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 13,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Macchine per ghiaccio e relativi filtri mantenuti in condizioni igieniche adeguate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 14,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Impianto spillatura bevande e bombole CO2 in sicurezza con controlli periodici documentati?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 15,
      section: ChecklistSection.premises_equipment,
      area: "Stoccaggio",
      question: "Magazzino bevande/alimenti ordinato con separazione prodotti alimentari e chimici?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 16,
      section: ChecklistSection.premises_equipment,
      area: "Stoccaggio",
      question: "Prodotti e semilavorati etichettati con data apertura/scadenza interna quando necessario?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 17,
      section: ChecklistSection.premises_equipment,
      area: "Spogliatoi e servizi",
      question: "Servizi igienici personale/clienti adeguati e mantenuti in condizioni igieniche idonee?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 18,
      section: ChecklistSection.premises_equipment,
      area: "Rifiuti",
      question: "Gestione rifiuti con contenitori idonei, differenziati e regolare svuotamento?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 19,
      section: ChecklistSection.premises_equipment,
      area: "Rifiuti",
      question: "Vetro e imballaggi gestiti in sicurezza evitando accumuli in aree operative?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: barPremisesTemplate.id,
      orderIndex: 20,
      section: ChecklistSection.premises_equipment,
      area: "Infestanti",
      question: "Piano derattizzazione/disinfestazione attivo con evidenze di monitoraggio periodico?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
  ];

  const barProcedureItems = [
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Manuale HACCP aggiornato e coerente con attivita reali (caffetteria, bevande, alimenti pronti)?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Analisi pericoli e punti di controllo definiti per prodotti freddi/caldi, latte e ghiaccio?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Registri temperature frigoriferi/vetrine compilati regolarmente e verificabili?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Procedure di controllo latte, creme e prodotti deperibili applicate con evidenze?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Gestione igienica ghiaccio alimentare definita (produzione, prelievo, conservazione)?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.procedures_hygiene,
      area: "Allergeni",
      question: "Elenco allergeni aggiornato e comunicato al consumatore per alimenti e bevande somministrate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.procedures_hygiene,
      area: "Allergeni",
      question: "Procedure operative per prevenire contaminazioni crociate allergeniche applicate al banco?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.procedures_hygiene,
      area: "Rintracciabilita",
      question: "Tracciabilita lotti e fornitori disponibile per alimenti, ingredienti e bevande?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 9,
      section: ChecklistSection.procedures_hygiene,
      area: "Rintracciabilita",
      question: "Procedura interna per ritiro/richiamo prodotti non conformi formalizzata e nota al personale?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 10,
      section: ChecklistSection.procedures_hygiene,
      area: "Ricevimento merci",
      question: "Controlli in accettazione merci su temperatura, integrita imballi e scadenze eseguiti?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 11,
      section: ChecklistSection.procedures_hygiene,
      area: "Ricevimento merci",
      question: "Respingimento merci non conformi gestito con procedura documentata?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 12,
      section: ChecklistSection.procedures_hygiene,
      area: "Preparazioni banco",
      question: "Preparazione panini/snack e guarnizioni con separazione utensili e superfici pulite?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 13,
      section: ChecklistSection.procedures_hygiene,
      area: "Preparazioni banco",
      question: "Tempi di permanenza a temperatura ambiente per alimenti deperibili ridotti e controllati?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 14,
      section: ChecklistSection.procedures_hygiene,
      area: "Igiene personale",
      question: "Personale con abbigliamento idoneo e comportamenti igienici adeguati durante il servizio?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 15,
      section: ChecklistSection.procedures_hygiene,
      area: "Igiene personale",
      question: "Procedura lavaggio mani applicata con disponibilita di detergente e asciugatura igienica?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 16,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Piano pulizie/sanificazioni del banco, macchina caffe, lavabicchieri e attrezzature formalizzato?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 17,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Prodotti detergenti/disinfettanti etichettati e conservati separatamente dagli alimenti?",
      defaultSeverity: 3,
      defaultSanctionable: false,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 18,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Sanificazione bicchieri e utensili verificata con criteri minimi di efficacia?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 19,
      section: ChecklistSection.procedures_hygiene,
      area: "Formazione HACCP",
      question: "Formazione HACCP del personale valida e documentata per tutti gli addetti coinvolti?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: barProceduresTemplate.id,
      orderIndex: 20,
      section: ChecklistSection.procedures_hygiene,
      area: "Miglioramento",
      question: "Registro NC interne con azioni correttive e verifica delle chiusure disponibile?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
  ];

  const hotelPremisesItemsBase = [
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Layout hotel idoneo con separazione flussi ospiti, personale, lavanderia e deposito rifiuti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Pavimenti, pareti, soffitti e corrimani in buono stato senza rischi di inciampo o caduta?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Scale, corridoi e uscite mantenuti liberi da ostacoli con segnaletica visibile?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Impianto elettrico conforme e quadro generale protetto con verifiche periodiche documentate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Impianto idrico e acqua potabile disponibili in tutte le aree servizio e colazione?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Impianti termici/climatizzazione manutenuti con controlli e registri disponibili?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza antincendio",
      question: "Estintori, idranti e presidi antincendio presenti e sottoposti a manutenzione entro scadenza?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza antincendio",
      question: "Piano emergenza incendio, compartimentazioni e vie di esodo aggiornati e coerenti con i piani?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 9,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza antincendio",
      question: "Illuminazione di emergenza e segnaletica sicurezza funzionanti e periodicamente verificate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 10,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza lavoro",
      question: "Cassetta primo soccorso completa e facilmente accessibile nelle aree operative?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 11,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Attrezzature housekeeping e carrelli in condizioni sicure con manutenzioni registrate?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 12,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Lavanderia interna (se presente) con macchine sicure e procedure operative definite?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 13,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Cucina/office colazioni (se presenti) con frigoriferi e attrezzature alimentari efficienti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 14,
      section: ChecklistSection.premises_equipment,
      area: "Stoccaggio",
      question: "Magazzino alimenti e bevande separato da detergenti e materiali di pulizia?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 15,
      section: ChecklistSection.premises_equipment,
      area: "Stoccaggio",
      question: "Biancheria pulita separata da biancheria sporca con percorsi e aree dedicate?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 16,
      section: ChecklistSection.premises_equipment,
      area: "Servizi",
      question: "Servizi igienici personale e ospiti idonei con dotazioni minime e pulizia regolare?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 17,
      section: ChecklistSection.premises_equipment,
      area: "Servizi",
      question: "Ascensori/montacarichi con verifiche periodiche e documentazione tecnica disponibile?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 18,
      section: ChecklistSection.premises_equipment,
      area: "Rifiuti",
      question: "Rifiuti urbani e speciali gestiti con aree dedicate, contenitori idonei e frequenze di ritiro adeguate?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 19,
      section: ChecklistSection.premises_equipment,
      area: "Infestanti",
      question: "Piano derattizzazione/disinfestazione attivo con monitoraggi periodici tracciati?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelPremisesTemplate.id,
      orderIndex: 20,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza lavoro",
      question: "Valutazione rischio movimentazione carichi e posture per housekeeping formalizzata e attuata?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
  ];

  const hotelProcedureItemsBase = [
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Manuale HACCP aggiornato per area colazioni, bar interno e somministrazione alimenti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Analisi pericoli e punti di controllo definiti per buffet colazioni e preparazioni semplici?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Registri temperature frigoriferi e conservazione alimenti compilati regolarmente?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Gestione alimenti deperibili in breakfast room con tempi/temperature controllati?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.procedures_hygiene,
      area: "Allergeni",
      question: "Informazioni allergeni disponibili e aggiornate per prodotti somministrati agli ospiti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.procedures_hygiene,
      area: "Allergeni",
      question: "Procedure per evitare contaminazioni crociate allergeniche nelle aree colazione applicate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.procedures_hygiene,
      area: "Rintracciabilita",
      question: "Tracciabilita lotti e fornitori disponibile per alimenti e bevande acquistate?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.procedures_hygiene,
      area: "Rintracciabilita",
      question: "Procedura ritiro/richiamo prodotti non conformi presente e applicabile?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 9,
      section: ChecklistSection.procedures_hygiene,
      area: "Ricevimento merci",
      question: "Controllo ricevimento merci con verifica integrita imballi, scadenze e temperature?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 10,
      section: ChecklistSection.procedures_hygiene,
      area: "Ricevimento merci",
      question: "Procedura di respingimento merci non conformi formalizzata e registrata?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 11,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Piano pulizie e sanificazioni per camere, aree comuni e breakfast room formalizzato?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 12,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Prodotti detergenti/disinfettanti etichettati, dosati e separati dagli alimenti?",
      defaultSeverity: 3,
      defaultSanctionable: false,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 13,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Procedure cambio biancheria, sanificazione superfici e tracciamento interventi applicate?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 14,
      section: ChecklistSection.procedures_hygiene,
      area: "Igiene personale",
      question: "Personale addetto a pulizie e somministrazione con abbigliamento idoneo e igiene personale adeguata?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 15,
      section: ChecklistSection.procedures_hygiene,
      area: "Igiene personale",
      question: "Procedura lavaggio mani con dotazioni disponibili nelle aree operative rispettata dal personale?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 16,
      section: ChecklistSection.procedures_hygiene,
      area: "Sicurezza lavoro",
      question: "Procedure sicurezza per housekeeping, manutenzione e reception formalizzate e diffuse?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 17,
      section: ChecklistSection.procedures_hygiene,
      area: "Sicurezza lavoro",
      question: "Consegna DPI e addestramento all'uso per addetti housekeeping/manutenzione documentati?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 18,
      section: ChecklistSection.procedures_hygiene,
      area: "Emergenze",
      question: "Procedure emergenza e antincendio note al personale con prove periodiche registrate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 19,
      section: ChecklistSection.procedures_hygiene,
      area: "Formazione",
      question: "Formazione sicurezza e HACCP del personale aggiornata e verificabile?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: hotelProceduresTemplate.id,
      orderIndex: 20,
      section: ChecklistSection.procedures_hygiene,
      area: "Miglioramento",
      question: "Registro non conformita interne con azioni correttive, responsabili e tempi di chiusura?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
  ];

  const pastryPremisesItemsBase = [
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Layout laboratorio e banco vendita con separazione flussi sporco/pulito e aree dedicate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Pavimenti, pareti e soffitti integri, lavabili e mantenuti in condizioni igieniche adeguate?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.premises_equipment,
      area: "Locali",
      question: "Porte e finestre con protezioni anti infestanti e assenza di varchi critici?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Impianto elettrico laboratorio conforme, sicuro e con verifiche periodiche documentate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Impianto idrico con acqua potabile disponibile e punti lavamani dedicati e funzionanti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.premises_equipment,
      area: "Impianti",
      question: "Aspirazione e ventilazione in area cottura/forni adeguate e manutenute?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza antincendio",
      question: "Presidi antincendio presenti, accessibili e manutenuti entro scadenza?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza antincendio",
      question: "Vie di esodo libere e segnaletica emergenza adeguata in laboratorio e area vendita?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 9,
      section: ChecklistSection.premises_equipment,
      area: "Sicurezza lavoro",
      question: "Cassetta di primo soccorso completa e disponibile per il personale?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 10,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Forni, impastatrici e planetarie con protezioni integre e manutenzione registrata?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 11,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Sfogliatrici, taglierine e attrezzature con organi in movimento dotate di sicurezza efficace?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 12,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Celle frigorifere, abbattitore e frigoriferi funzionanti con termometri affidabili?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 13,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Vetrine refrigerate per dolci/gelati efficienti con controllo temperature documentabile?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 14,
      section: ChecklistSection.premises_equipment,
      area: "Attrezzature",
      question: "Pastorizzatore, mantecatore e macchinari gelateria (se presenti) in condizioni igienico-funzionali idonee?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 15,
      section: ChecklistSection.premises_equipment,
      area: "Stoccaggio",
      question: "Materie prime alimentari stoccate correttamente con separazione da chimici e materiali non alimentari?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 16,
      section: ChecklistSection.premises_equipment,
      area: "Stoccaggio",
      question: "Semilavorati e prodotti finiti etichettati con data produzione/apertura e scadenza interna?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 17,
      section: ChecklistSection.premises_equipment,
      area: "Servizi",
      question: "Area lavaggio utensili separata e organizzata con flussi idonei per evitare contaminazioni?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 18,
      section: ChecklistSection.premises_equipment,
      area: "Rifiuti",
      question: "Gestione rifiuti e scarti produttivi con contenitori idonei e frequenze di smaltimento adeguate?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 19,
      section: ChecklistSection.premises_equipment,
      area: "Mezzi",
      question: "Mezzi di trasporto per consegne (se presenti) puliti, idonei e con catena del freddo garantita quando richiesta?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: pastryPremisesTemplate.id,
      orderIndex: 20,
      section: ChecklistSection.premises_equipment,
      area: "Infestanti",
      question: "Piano monitoraggio infestanti (PMP) attivo con report periodici e azioni correttive tracciate?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
  ];

  const pastryProcedureItemsBase = [
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 1,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Manuale HACCP aggiornato e coerente con processi di pasticceria/gelateria effettivamente svolti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 2,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Analisi pericoli e punti di controllo critici (CCP/CP) definiti per creme, gelati e farciture?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 3,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Registri temperature celle, vetrine e abbattitori compilati regolarmente e verificabili?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 4,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Controlli su pastorizzazione/mantecazione gelato e raffreddamento creme formalizzati e registrati?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 5,
      section: ChecklistSection.procedures_hygiene,
      area: "HACCP",
      question: "Gestione ingredienti ad alto rischio (uova crude, latte, panna) con procedure e limiti operativi definiti?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 6,
      section: ChecklistSection.procedures_hygiene,
      area: "Allergeni",
      question: "Mappatura allergeni aggiornata su ricette, ingredienti e prodotti esposti al banco?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 7,
      section: ChecklistSection.procedures_hygiene,
      area: "Allergeni",
      question: "Procedure per prevenire contaminazione crociata allergeni adottate nelle fasi di produzione e servizio?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 8,
      section: ChecklistSection.procedures_hygiene,
      area: "Rintracciabilita",
      question: "Tracciabilita lotti ingredienti e semilavorati garantita con registrazioni complete?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 9,
      section: ChecklistSection.procedures_hygiene,
      area: "Rintracciabilita",
      question: "Procedura ritiro/richiamo prodotto formalizzata, testata e nota al personale?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 10,
      section: ChecklistSection.procedures_hygiene,
      area: "Ricevimento merci",
      question: "Controlli in accettazione su temperature, integrita imballi, allergeni e scadenze sempre effettuati?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 11,
      section: ChecklistSection.procedures_hygiene,
      area: "Ricevimento merci",
      question: "Respingimento merci non conformi gestito con procedura documentata e registrazioni?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 12,
      section: ChecklistSection.procedures_hygiene,
      area: "GMP",
      question: "Standard GMP applicati nelle fasi di pesatura, impasto, cottura, farcitura e confezionamento?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 13,
      section: ChecklistSection.procedures_hygiene,
      area: "Igiene personale",
      question: "Personale con abbigliamento idoneo, DPI e comportamento igienico conforme alle procedure?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 14,
      section: ChecklistSection.procedures_hygiene,
      area: "Igiene personale",
      question: "Protocollo lavaggio mani e gestione guanti rispettato in tutte le fasi produttive?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 15,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Piano pulizie e sanificazioni di laboratorio, celle, utensili e banco vendita formalizzato e applicato?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 16,
      section: ChecklistSection.procedures_hygiene,
      area: "Pulizie",
      question: "Prodotti detergenti/disinfettanti idonei, etichettati e conservati separatamente dagli alimenti?",
      defaultSeverity: 3,
      defaultSanctionable: false,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 17,
      section: ChecklistSection.procedures_hygiene,
      area: "Controlli strumentali",
      question: "Taratura/verifica periodica di termometri, sonde e bilance con evidenze disponibili?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 18,
      section: ChecklistSection.procedures_hygiene,
      area: "Miglioramento",
      question: "Gestione non conformita interne con azioni correttive (CAPA), responsabili e tempi monitorati?",
      defaultSeverity: 2,
      defaultSanctionable: false,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 19,
      section: ChecklistSection.procedures_hygiene,
      area: "Sicurezza lavoro",
      question: "Procedure sicurezza per uso di forni, lame, impastatrici e movimentazione carichi formalizzate e applicate?",
      defaultSeverity: 4,
      defaultSanctionable: true,
    },
    {
      templateId: pastryProceduresTemplate.id,
      orderIndex: 20,
      section: ChecklistSection.procedures_hygiene,
      area: "Formazione",
      question: "Formazione HACCP, GMP, PMP e sicurezza del personale aggiornata e verificabile?",
      defaultSeverity: 3,
      defaultSanctionable: true,
    },
  ];

  const hotelPremisesDomainByOrder: Record<number, ComplianceDomain> = {
    1: ComplianceDomain.both,
    2: ComplianceDomain.safety,
    3: ComplianceDomain.safety,
    4: ComplianceDomain.safety,
    5: ComplianceDomain.both,
    6: ComplianceDomain.safety,
    7: ComplianceDomain.safety,
    8: ComplianceDomain.safety,
    9: ComplianceDomain.safety,
    10: ComplianceDomain.safety,
    11: ComplianceDomain.safety,
    12: ComplianceDomain.safety,
    13: ComplianceDomain.haccp,
    14: ComplianceDomain.haccp,
    15: ComplianceDomain.safety,
    16: ComplianceDomain.safety,
    17: ComplianceDomain.safety,
    18: ComplianceDomain.safety,
    19: ComplianceDomain.both,
    20: ComplianceDomain.safety,
  };

  const hotelProcedureDomainByOrder: Record<number, ComplianceDomain> = {
    1: ComplianceDomain.haccp,
    2: ComplianceDomain.haccp,
    3: ComplianceDomain.haccp,
    4: ComplianceDomain.haccp,
    5: ComplianceDomain.haccp,
    6: ComplianceDomain.haccp,
    7: ComplianceDomain.haccp,
    8: ComplianceDomain.haccp,
    9: ComplianceDomain.haccp,
    10: ComplianceDomain.haccp,
    11: ComplianceDomain.both,
    12: ComplianceDomain.both,
    13: ComplianceDomain.safety,
    14: ComplianceDomain.both,
    15: ComplianceDomain.both,
    16: ComplianceDomain.safety,
    17: ComplianceDomain.safety,
    18: ComplianceDomain.safety,
    19: ComplianceDomain.both,
    20: ComplianceDomain.both,
  };

  const hotelPremisesItems = hotelPremisesItemsBase.map((item) => ({
    ...item,
    domain: hotelPremisesDomainByOrder[item.orderIndex] ?? ComplianceDomain.both,
  }));

  const hotelProcedureItems = hotelProcedureItemsBase.map((item) => ({
    ...item,
    domain: hotelProcedureDomainByOrder[item.orderIndex] ?? ComplianceDomain.both,
  }));

  const pastryPremisesDomainByOrder: Record<number, ComplianceDomain> = {
    1: ComplianceDomain.both,
    2: ComplianceDomain.both,
    3: ComplianceDomain.haccp,
    4: ComplianceDomain.safety,
    5: ComplianceDomain.both,
    6: ComplianceDomain.both,
    7: ComplianceDomain.safety,
    8: ComplianceDomain.safety,
    9: ComplianceDomain.safety,
    10: ComplianceDomain.safety,
    11: ComplianceDomain.safety,
    12: ComplianceDomain.haccp,
    13: ComplianceDomain.haccp,
    14: ComplianceDomain.haccp,
    15: ComplianceDomain.haccp,
    16: ComplianceDomain.haccp,
    17: ComplianceDomain.both,
    18: ComplianceDomain.both,
    19: ComplianceDomain.both,
    20: ComplianceDomain.both,
  };

  const pastryProcedureDomainByOrder: Record<number, ComplianceDomain> = {
    1: ComplianceDomain.haccp,
    2: ComplianceDomain.haccp,
    3: ComplianceDomain.haccp,
    4: ComplianceDomain.haccp,
    5: ComplianceDomain.haccp,
    6: ComplianceDomain.haccp,
    7: ComplianceDomain.haccp,
    8: ComplianceDomain.haccp,
    9: ComplianceDomain.haccp,
    10: ComplianceDomain.haccp,
    11: ComplianceDomain.haccp,
    12: ComplianceDomain.both,
    13: ComplianceDomain.both,
    14: ComplianceDomain.both,
    15: ComplianceDomain.both,
    16: ComplianceDomain.both,
    17: ComplianceDomain.both,
    18: ComplianceDomain.both,
    19: ComplianceDomain.safety,
    20: ComplianceDomain.both,
  };

  const pastryPremisesItems = pastryPremisesItemsBase.map((item) => ({
    ...item,
    domain: pastryPremisesDomainByOrder[item.orderIndex] ?? ComplianceDomain.both,
  }));

  const pastryProcedureItems = pastryProcedureItemsBase.map((item) => ({
    ...item,
    domain: pastryProcedureDomainByOrder[item.orderIndex] ?? ComplianceDomain.both,
  }));

  for (const item of [
    ...generalItems,
    ...restaurantPremisesItems,
    ...restaurantProcedureItems,
    ...barPremisesItems,
    ...barProcedureItems,
    ...hotelPremisesItems,
    ...hotelProcedureItems,
    ...pastryPremisesItems,
    ...pastryProcedureItems,
  ]) {
    const explicitDomain = (item as { domain?: ComplianceDomain }).domain;
    await prisma.checklistItem.create({
      data: {
        ...item,
        domain: explicitDomain ?? inferChecklistDomain(item.area, item.question),
      },
    });
  }

  await prisma.documentTemplate.deleteMany({});

  const documentTemplates = [
    {
      name: "Visura camerale aggiornata",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Planimetria aggiornata dei locali",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Relazione tecnica attivita",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "UNILAV dipendenti",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "DVR e allegati (rischi specifici ristorazione)",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Nomina RSPP e deleghe sicurezza",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Nomina addetti antincendio e primo soccorso",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Attestati formazione sicurezza lavoratori",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Sorveglianza sanitaria e giudizi di idoneita",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Dichiarazioni conformita impianti elettrico e gas",
      isGeneral: true,
      isRequired: true,
    },
    {
      name: "Registro manutenzioni attrezzature",
      isGeneral: true,
      isRequired: false,
    },
    {
      name: "SCIA / notifica sanitaria attivita alimentare",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Manuale HACCP aggiornato",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Analisi pericoli e piano CCP/CP",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Registro temperature celle/frigoriferi/abbattitore",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Registro temperature cottura/rigenerazione",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Piano pulizie e sanificazioni con registrazioni",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Procedure gestione allergeni e menu allergeni",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Schede tracciabilita lotti e fornitori",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Procedura ritiro/richiamo alimenti",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Attestati formazione HACCP personale",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Contratto e rapporti derattizzazione/disinfestazione",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Certificazioni cappa/aspirazione e manutenzioni",
      isGeneral: false,
      isRequired: false,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "Documenti gestione oli esausti e smaltimento",
      isGeneral: false,
      isRequired: false,
      atecoCode: "56.10.11",
      macroGroup: "RISTORANTI",
    },
    {
      name: "SCIA / notifica sanitaria attivita bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Manuale HACCP bar aggiornato",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Analisi pericoli e punti di controllo bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Registro temperature frigoriferi e vetrine bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Procedura e controlli gestione ghiaccio alimentare",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Piano pulizie e sanificazioni banco/macchina caffe/lavabicchieri",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Procedure gestione allergeni per alimenti e bevande",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Schede tracciabilita lotti e fornitori bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Procedura ritiro/richiamo prodotti bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Attestati formazione HACCP personale bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Registro manutenzioni impianto spillatura e bombole CO2",
      isGeneral: false,
      isRequired: false,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "Contratto e rapporti derattizzazione/disinfestazione bar",
      isGeneral: false,
      isRequired: true,
      atecoCode: "56.30",
      macroGroup: "BAR",
    },
    {
      name: "SCIA / titolo autorizzativo struttura ricettiva",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.safety,
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
    },
    {
      name: "Valutazione rischio incendio struttura ricettiva",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.safety,
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
    },
    {
      name: "Piano emergenza ed evacuazione hotel",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.safety,
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
    },
    {
      name: "Registro controlli antincendio e illuminazione emergenza",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.safety,
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
    },
    {
      name: "Registro manutenzione ascensori/montacarichi",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.safety,
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
    },
    {
      name: "Manuale HACCP area colazioni/bar interno",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.haccp,
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
    },
    {
      name: "Analisi pericoli e punti di controllo buffet colazioni",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.haccp,
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
    },
    {
      name: "Registro temperature frigoriferi e conservazione alimenti hotel",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.haccp,
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
    },
    {
      name: "Procedure allergeni per servizio colazioni",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.haccp,
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
    },
    {
      name: "Piano pulizie e sanificazioni camere/aree comuni/colazioni",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.both,
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
    },
    {
      name: "Tracciabilita lotti fornitori alimenti e bevande hotel",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.haccp,
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
    },
    {
      name: "Attestati formazione HACCP e sicurezza personale hotel",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.both,
      atecoCode: "55.10.00",
      macroGroup: "HOTEL",
    },
    {
      name: "SCIA / notifica sanitaria laboratorio pasticceria-gelateria",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.haccp,
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
    },
    {
      name: "Manuale HACCP pasticceria-gelateria aggiornato",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.haccp,
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
    },
    {
      name: "Analisi pericoli e CCP/CP per creme, farciture e gelati",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.haccp,
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
    },
    {
      name: "Registro temperature celle, abbattitore e vetrine refrigerate",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.haccp,
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
    },
    {
      name: "Registro processi pastorizzazione/mantecazione gelato (se applicabile)",
      isGeneral: false,
      isRequired: false,
      domain: ComplianceDomain.haccp,
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
    },
    {
      name: "Elenco allergeni e ricettari aggiornati per banco vendita",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.haccp,
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
    },
    {
      name: "Schede tracciabilita lotti ingredienti e semilavorati",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.haccp,
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
    },
    {
      name: "Procedura ritiro/richiamo prodotti di pasticceria-gelateria",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.haccp,
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
    },
    {
      name: "Piano pulizie e sanificazioni laboratorio, attrezzature e banco",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.both,
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
    },
    {
      name: "Piano monitoraggio infestanti (PMP) e rapporti intervento",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.both,
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
    },
    {
      name: "Registro manutenzioni forni, impastatrici, sfogliatrici e celle",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.safety,
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
    },
    {
      name: "Valutazione rischio attrezzature da taglio/ustioni e procedure DPI",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.safety,
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
    },
    {
      name: "Attestati formazione HACCP, GMP, PMP e sicurezza personale laboratorio",
      isGeneral: false,
      isRequired: true,
      domain: ComplianceDomain.both,
      atecoCode: "56.10.30",
      macroGroup: "PASTICCERIA_GELATERIA",
    },
  ];

  await prisma.documentTemplate.createMany({
    data: documentTemplates.map((doc) => ({
      name: doc.name,
      description: `Template documento: ${doc.name}`,
      domain: (doc as { domain?: ComplianceDomain }).domain ?? inferDocumentDomain(doc.name),
      isGeneral: doc.isGeneral,
      isRequired: doc.isRequired,
      atecoCode: doc.atecoCode ?? null,
      macroGroup: doc.macroGroup ?? null,
      isActive: true,
    })),
  });

  console.log("Seed completato.");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
